### ISSUE TITLE
External benchmarking on Match Zoo

### ISSUE THREAD

**Issue by aneesh-joshi** [faneshion/MatchZoo#106] opened 2018-05-21 13:40 UTC
Hi,
I am trying to establish  benchmark results on all the document similarity models at MatchZoo.
While there are some established benchmarks, it would be good if we had a MatchZoo-code independent system for evaluating results.

Eg:
```
    input_data -> MZ -> result_data
    result_data - > independent_evaluation_code -> metric scores (Example: ndcg@k, map, etc.)
```

The current scenario is that the evaluation code is strongly ingrained in the MZ code, which can cause problems with different commits over time. As seen in https://github.com/faneshion/MatchZoo/issues/99

**1. Is there a way already for doing this?**
    I assume TREC is for that. Could someone direct me on how to use it?
**2. Could some one direct me on how to go about making such an evaluation code?**
(Once developed, I will push it back into MZ and it could be like a Continuous Integration test.)

What do you think, @faneshion @yangliuy @bwanglzu @millanbatra @mandroid6?

Thanks!

**Comment by bwanglzu** [comment] 2018-05-21 14:30
Guess you are looking for [trec_eval](https://trec.nist.gov/trec_eval/)? Written in `c`, not very user-friendly, but has been used for several years.

The problem is Matchzoo actually have no unit test.

I used to create an issue #82 sadly get no response :( so I closed the issue

**Comment by aneesh-joshi** [comment] 2018-05-21 17:09
@bwanglzu 
Indeed, trec_eval is difficult to understand.
MZ saves the evaluation in trec_eval-like format. But it's not very clear about how to use it.

**Comment by yangliuy** [comment] 2018-05-21 17:30
I also think [trec_eval](https://trec.nist.gov/trec_eval/) is a good option. You can also use [Galago Eval](https://sourceforge.net/p/lemur/wiki/Galago%20Evaluation/) for this purpose. 

@bwanglzu I just tried to do the settings you suggested on [travis-CI](https://travis-ci.org/yangliuy/MatchZoo/). But I am not very sure whether I did it in the correct way. I didn't use this platform before. Do you mean it could do automatic testing for MatchZoo after each commits ? In that case, do we need to prepare the testing cases ?

**Comment by bwanglzu** [comment] 2018-05-21 17:31
@yangliuy Exactly, let me explain, one second.

**Comment by aneesh-joshi** [comment] 2018-05-21 17:43
@yangliuy 
How do we get matchzoo to create the qrel and ranklist files?

It creates predict.test.wikiqa.txt but that is in some other format

**Comment by yangliuy** [comment] 2018-05-21 17:54
@aneesh-joshi You can specify the predicted score file in the TREC_EVAL format. For the qrel file, you can generate it with the input relation file of testing data easily.

**Comment by bwanglzu** [comment] 2018-05-29 10:37
I'll close this for now, in MatchZoo 2.0 we'll have a better input-output-evaluation pipeline.

**Comment by aneesh-joshi** [comment] 2018-05-29 11:08
actually,
I wrote a simple script which does the job partially.

The `predict` phase on `main.py` outputs `y_predicted` and  `y_true` for some of the test data.
My script goes through that and provides metrics.

**Comment by aneesh-joshi** [comment] 2018-05-29 12:37
```
def mz_eval(mz_output_file):
    """Evaluates the metrics on a TREC format file output by MatchZoo

    parameters:
    ==========
    mz_output_file : string
        path to MatchZoo output TREC format file

    file_to_write : string
        where the results of the evaluation should be stored
        ignore if it is None
    """

    with open(mz_output_file) as f:
        df = pd.read_csv(f, sep='\t')

    Y_true = []
    Y_pred = []

    # group the results based on question id
    for Question, Answer in df.groupby('QuestionID').apply(dict).items():
        this_y_true = []
        this_y_pred = []
        for d, l in zip(Answer['e'], Answer['g']):
            this_y_pred.append(d)
            this_y_true.append(l)
        Y_pred.append(this_y_pred)
        Y_true.append(this_y_true)

    results = get_metric_results(Y_true, Y_pred)

    print("Results of evaluating on mz_eval:")
    print(results)

if __name__ == '__main__':
    mz_eval('predict.test.wikiqa.txt')

```

**Comment by bwanglzu** [comment] 2018-05-29 12:41
@aneesh-joshi Thanks! Maybe in 2.0 we'll reuse your evaluation code, please keep an eye on the development of MatchZoo 2.0! (it's on `2.0` branch, and all issue labeled with 2.0 are sub tasks)!

**Comment by aneesh-joshi** [comment] 2018-05-29 12:58
@bwanglzu 

Oh
That's great! I'll look out for some issues which I can fix.

I have a question and some suggestions.
question : the `predict.test.wikiqa.txt` has only 2341 entries whereas `wikiqa-test.tsc` has 6 thousand.
Why is it so?

Suggestions:
1. add a contributing.md for people who want to contribute. it should have instructions on how to make the build environment, etc
2. Include pep8 formatting as mandatory in the continuous integration
3. Currently the models are unusable. For example, I have want to use the DSSM saved model. If I want to  test the wikiqa trained model with my own query-doc pairs, I will have to go through the word-dict, tri-dict txts and figure out a way of translating my sentence, say "what is a model" into the correct input like `[34, 45, ...]`  An easier translation method would be great
4. Include instructions for making a build environment. either virtual env or conda. This will help with reproducability. Even a docker image would be great. Add an environment.yml or a requirements.txt
5. make MZ OS independent. Currently MZ needs Linux/Unix. It would be better to run python scripts instead of the bash scripts.

Hope these help.

**Comment by bwanglzu** [comment] 2018-05-29 13:37
haha, @aneesh-joshi Thanks for your suggestion!

For the question, I'll @faneshion to answer.

For suggestions:

1. Nice, we'll create an issue on contribution.md!
2. PEP8 in the current version of MZ is not mandatory, but for 2.0 is mandatory! Switch to branch `2.0` and take a look at `Makefile`, it will run `flake8` and `Makefile` will be called in `.travis.yml`!
3.  Great suggestion! Take a look at [project board](https://github.com/faneshion/MatchZoo/projects/1) our ambitions, we'll look into the best approach to do this!
4. Docker will be a good idea, we'll create something like this after 2.0 is in place, but it's not in our priority list due to the fact that we're all students and spending spare time on this project :) .
5. This is also in our 2.0 ambition, we'll figure out a good way to handle os specific situation!
6. We already have requirements.txt! You can run `make init` to install all the dependencies! Even happens in our master branch.

Actually, we also set up a document server for 2.0 which is available at [here](https://matchzoo.readthedocs.io/en/2.0/)!

We're not building 2.0 from scratch, but I hope it will be a 'brand-new' one from the user experience perspective!

We're now writing the engine for 2.0, hopefully in the near future we'll release some tasks, hopefully, you can keep contributing to matchzoo!

**Comment by aneesh-joshi** [comment] 2018-05-29 14:48
@bwanglzu 
I appreciate your help and quick responses.
I too am a student doing his Google Summer of Code using MatchZoo for bench marking and code inspiration/direction.

**Comment by aneesh-joshi** [comment] 2018-05-29 15:02
Also, I did open the issue before, but I really feel like WeChat is a bit limited.
gitter or telegram would make it easier to communicate.

**Comment by bwanglzu** [comment] 2018-05-29 15:04
@aneesh-joshi As you might know that ... GFW (great firewall) has banned a lot of applications in China, including gitter, telegram or even slack...

**Comment by faneshion** [comment] 2018-05-29 15:33
@aneesh-joshi Thanks for your all constructive suggestions. For your question about test data in WikiQA, there are a number of questions have no positive labels. We removed all these question in test as is done in https://github.com/EastonWang/WikiQA-Selection.

**Comment by aneesh-joshi** [comment] 2018-05-29 19:13
thanks for the answer, @faneshion 
I never thought there more than 3000 queries with no answers in their test split!

@bwanglzu Oh, I didn't know about the GFW.
The wechat group is unusually silent and I can't figure out if there is anybody there.

**Comment by bwanglzu** [comment] 2018-05-30 07:38
I was not in that wechat group:(

**Comment by aneesh-joshi** [comment] 2018-05-30 10:27
based on the script I mentioned before,
I get the following results


Method | map | ndcg@1 | ndcg@3 | ndcg@5 | ndcg@10 | ndcg@20
-- | -- | -- | -- | -- | -- | --
anmm | 0.60231 | 0.476793 | 0.617116 | 0.659008 | 0.710042 | 0.71779
arci | 0.568631 | 0.451477 | 0.563715 | 0.637976 | 0.672469 | 0.690647
cdssm | 0.523825 | 0.341772 | 0.54126 | 0.596421 | 0.638492 | 0.656304
conv_knrm_ranking | 0.569223 | 0.43038 | 0.587006 | 0.636489 | 0.684447 | 0.692889
drmm | 0.587125 | 0.447257 | 0.597009 | 0.646743 | 0.692769 | 0.706267
drmm_tks | 0.631183 | 0.506329 | 0.641376 | 0.690293 | 0.727095 | 0.73819
dssm | 0.526801 | 0.341772 | 0.537857 | 0.597434 | 0.645009 | 0.656767
duet | 0.592516 | 0.451477 | 0.608629 | 0.657476 | 0.701125 | 0.711556
knrm_ranking | 0.501507 | 0.35865 | 0.499058 | 0.559678 | 0.619065 | 0.636557
matchpyramid | 0.605238 | 0.447257 | 0.62509 | 0.676466 | 0.714582 | 0.721466
mvlstm | 0.585831 | 0.459916 | 0.597372 | 0.648699 | 0.692848 | 0.705998

I couldn't add `arcii` since the `predict.test.wikiqa.txt` gives `nan`

**Comment by bwanglzu** [comment] 2018-06-04 14:01
I'm going to close this one, please refer to #147 , thanks!

**Closed by bwanglzu** 2018-06-04 14:01 UTC
Labels: enhancement
